ddpkts_oxid.home:
    path: /
    defaults: { _controller: DdpktsOXIDBundle:Default:index }

ongr_search:
    pattern: /search
    methods:  [GET]
    defaults:
        _controller: ONGRFilterManagerBundle:Manager:manager
        managerName: "product_list"
        template: "DdpktsOXIDBundle:Product:search.html.twig"

ongr_content_snippet:
    resource: @ONGRContentBundle/Resources/config/routing.yml

### Proxy routes
#Category
_ongr_category_tree:
    pattern:  /_proxy/tree/{theme}/{maxLevel}/{partialTree}/{selectedCategory}
    defaults:
        _controller: DdpktsOXIDBundle:Category:categoryTree
        theme: "top"
        maxLevel: 2
        partialTree: "pt"
        selectedCategory: null
